name: Proctor - A/B Testing Framework by Indeed
# https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM #Enable GitHub Flavored Markdown (fenced code blocks)
    auto_ids: true
    hard_wrap: false
    syntax_highlighter: rouge

    exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile.rb', 'README.md']

plugins:
    [jekyll-gist]

# jekyll serve --watch --baseurl=
# baseurl: "https://indeedeng.github.io/proctor"
# baseurl: "https://agrover-indeed.github.io/proctor"
# baseurl: "https://tate-indeed.github.io/proctor-tate-working"

